module.exports = [
  'CHANGE_CHANNEL',
  'WARNING',
  'CHANNEL_CREATED',
  'CHANNEL_DISCONNECTED',
  'PAIRING_PROGRESS',
  'PAIRING_TIMEOUT',
  'REMOTE_CONNECTED',
  'REMOTE_PAIRED',
  'TIMER_TICK',
  'SLIDE_IDX_CHANGED_FROM_REMOTE',
  'SLIDE_IDX_CHANGED_FROM_PRESENTATION',
  'SLIDE_DECK_RESET',
  'SELECTED_SLIDE_CHANGED'
].reduce((acc, actionType) => {
  acc[actionType] = actionType;
  return acc;
}, {});
